### ISSUE TITLE
How about rxjava2? Any plans? 

### ISSUE THREAD

**Issue by Rainer-Lang** [trivago/Heimdall.droid#43]

**Comment by Gi-lo** [comment]
@Rainer-Lang This should definitely be tackled. Though I am not quite sure in what way or when. We'll discuss this next month within the tram and post our plan/solution here afterwards.

**Comment by eyedol** [comment]
I was thinking about this as well. Perhaps as a separate module so both rxjava 1 and 2 could co-exist? Anyway, keeping an eye on this as I'm interested in how it progresses.

**Comment by Rainer-Lang** [comment]
@Gi-lo Any news?

**Comment by Gi-lo** [comment]
Nope, nothing yet. We still haven't had the chance to think about it yet.

**Comment by AHarazim** [comment]
@Gi-lo Any news now?
